### ISSUE TITLE
Particles not added to page

### ISSUE THREAD

**Issue by Kore-Development** [samerton/Nameless-Particles#1]
The particles are not being added to the header. [My website.](https://www.pqtato.pw/n/) Let me know if you need any files.

**Comment by samerton** [comment]
Hi,

This can happen if your template isn't writable for the PHP process.

As you're using the Default Revamp template, you can manually edit the file **custom/templates/*template*/navbar.tpl**, and *before* the line `<div class="ui masthead">`, add
```
<div id="particles-js"></div>
```
so it'll look like this:
```
<div id="particles-js"></div>
<div class="ui masthead .....
```

**Comment by Kore-Development** [comment]
It worked.

**Comment by Kore-Development** [comment]
By the way I use [PebbleHost](https://pebblehost.com/) and I'm guessing it set the permissions wrong
